"""Constants for the TorMeter menu UI."""

MENU_BAR_HEIGHT = 16
BORDER_WIDTH = 2
CLOSE_BTN_SIZE = 8
CLOSE_BTN_MARGIN = 4
MENU_BAR_SIDE_PADDING = 1
CONTENT_PADDING = 4
TOGGLE_W = 28
TOGGLE_H = 14
TOGGLE_RADIUS = 7
ROW_HEIGHT = 28
ARROW_W = 22
COG_W = 22
RESET_BTN_W = 18
RESET_BTN_H = 14
WINDOW_NAME = "TorMeter Menu"

EXCLUDED_FROM_SHOWALL = {"Overlay Master", "TorMeter Menu"}
